server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: varlogs
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log

    relabel_configs:
      - source_labels: [__path__]
        target_label: filename

      - source_labels: [filename]
        regex: (.+)\.log
        target_label: stream
        replacement: $1
        action: replace

      - action: labeldrop
        regex: service_name
